// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVtA0oRiWyQD0GdEJfN8axMusB1xBC3Bw',
    appId: '1:891522542953:web:a45021d2f8e3552a2061f8',
    messagingSenderId: '891522542953',
    projectId: 'flutter-chat-edb8e',
    authDomain: 'flutter-chat-edb8e.firebaseapp.com',
    databaseURL: 'https://flutter-chat-edb8e-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-chat-edb8e.appspot.com',
    measurementId: 'G-SW4CVRRSET',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhCaxkLUWwwqokLNE7KPHw6fKB59A-bgA',
    appId: '1:891522542953:android:8de8d6596edf60992061f8',
    messagingSenderId: '891522542953',
    projectId: 'flutter-chat-edb8e',
    databaseURL: 'https://flutter-chat-edb8e-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-chat-edb8e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHSqoUqUGlQTuNzO9QN5RmK4WmF0TBVo8',
    appId: '1:891522542953:ios:e31c3716736c97982061f8',
    messagingSenderId: '891522542953',
    projectId: 'flutter-chat-edb8e',
    databaseURL: 'https://flutter-chat-edb8e-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-chat-edb8e.appspot.com',
    iosClientId: '891522542953-du0djt5ph0us2soatckjil9aji28vhsv.apps.googleusercontent.com',
    iosBundleId: 'com.example.appChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHSqoUqUGlQTuNzO9QN5RmK4WmF0TBVo8',
    appId: '1:891522542953:ios:e31c3716736c97982061f8',
    messagingSenderId: '891522542953',
    projectId: 'flutter-chat-edb8e',
    databaseURL: 'https://flutter-chat-edb8e-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-chat-edb8e.appspot.com',
    iosClientId: '891522542953-du0djt5ph0us2soatckjil9aji28vhsv.apps.googleusercontent.com',
    iosBundleId: 'com.example.appChat',
  );
}
